// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:78d59f47-fe1e-4fbc-ba4d-cbbaae0afed7",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Am079G1mm",
    "aws_user_pools_web_client_id": "6t05vq7646efr5lcgf8tf252qg",
    "aws_mobile_analytics_app_id": "778dcabc4aa54149912d1b84280f8d8d",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_content_delivery_bucket": "goappv-hosting-mobilehub-1646875335",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d2k68pqd7d4m4x.cloudfront.net",
    "aws_cloud_logic_custom": [
        {
            "name": "myGoApi",
            "endpoint": "https://pzixftkvxe.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        },
        {
            "name": "apiperfil",
            "endpoint": "https://537u7jlyn9.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
