// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'us-east-1:de1d4955-f557-48e3-bdb9-e8a221fcd8e6';
var aws_cognito_region = 'us-east-1';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'goappv-hosting-mobilehub-1646875335';
var aws_content_delivery_bucket_region = 'us-east-1';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd2slsu56xxfbq.cloudfront.net';
var aws_dynamodb = 'enable';
var aws_dynamodb_all_tables_region = 'us-east-1';
var aws_dynamodb_table_schemas = [{"tableName":"goappv-mobilehub-1646875335-mytodos","attributes":[{"name":"userId","type":"S"},{"name":"todoId","type":"S"},{"name":"status","type":"S"},{"name":"todo","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"todoId"}];
var aws_mobile_analytics_app_id = '73e063e92079401a92af0ab2d472530a';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '156f3db2-133a-4f24-b08a-4da47ba1c903';
var aws_project_name = 'GoAppv1';
var aws_project_region = 'us-east-1';
var aws_resource_name_prefix = 'goappv-mobilehub-1646875335';
var aws_sign_in_enabled = 'enable';
var aws_user_pools = 'enable';
var aws_user_pools_id = 'us-east-1_UNrg4LfUO';
var aws_user_pools_mfa_type = 'OFF';
var aws_user_pools_web_client_id = 'd2sv5n7l5n0lvsq04lm10d502';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
